name: CI/CD Pipeline with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: clone-repo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Directory Contents
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build