name: CI/CD Pipeline with Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clone-repo:
    name: Clone Repository
    runs-on: ubuntu-latest
    steps:
      - name: Remove existing folder and clone repo
        run: |
          rm -rf react-app
          ls -la
          git clone https://github.com/ttrevor998/integracion-final react-app
          pwd
          ls -la
          cd react-app
          ls -la

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: clone-repo
    steps:
      - name: List Directory Contents
        run: ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build